# Uncomment the next line to define a global platform for your project
platform :ios, '13.6'

target 'EDUtilitiesDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
	
  # Pods for EDUtilitiesDemo
	pod 'EDDevUtilities'
  target 'EDUtilitiesDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'EDUtilitiesDemoUITests' do
    # Pods for testing
  end

end
